puts "The Students of my cohort at MA"
puts "----------------"
puts "Alex Bease"
puts "Alan Bridger"
puts "Arfah"
puts "Ben Hutchinson"
puts "Claudia"
puts "Chris Handley"
puts "Christopher Batts"
puts "Vaidas Mykolaitis"
puts "Peter Saxton"
puts "Edward Byne"
puts "Giorgia"
puts "Henrey Stanley"
puts "Izzy Markwick"
puts "Mihai Liviu Cojocar"
puts "Nick Dyer"
puts "Pavel Redics"
puts "Richard Lake"
puts "Roi Driscoll"
puts "Stephen Lloyd"
puts "Tom Groombridge"
puts "Attila"
puts "Anna Yanova"
#finally, we print the total number of students
print "Overall, we have "
#it's important to remember that print() doesn't add new line characters
print 9
puts " great students"